version: '3'

services:


  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
    networks:
      - kafka
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

networks:
  kafka: 


